const genreOptions = {
    fantasy: [
      "High Fantasy",
      "Dark Fantasy",
      "Urban Fantasy",
      "Romantic Fantasy",
      "Epic Fantasy",
      "Historical Fantasy",
      "Sword and Sorcery",
      "Fairy Tale Retelling",
      "Magical Realism",
      "Mythic Fantasy",
      "Portal Fantasy",
      "Low Fantasy",
    ],
  
    sciFi: [
      "Cyberpunk",
      "Space Opera",
      "Dystopian",
      "Utopian",
      "Post-Apocalyptic",
      "Time Travel",
      "Mecha / Robot",
      "Genetic Engineering",
      "Hard Science Fiction",
      "Military Sci-Fi",
      "AI / Machine Uprising",
      "Alternate Reality",
    ],
  
    mystery: [
      "Detective",
      "Cozy Mystery",
      "Police Procedural",
      "Crime Mystery",
      "Whodunit",
      "Psychological Mystery",
      "Historical Mystery",
      "Amateur Sleuth",
      "Forensic Mystery",
      "Legal Mystery",
      "Supernatural Mystery",
      "Locked Room",
    ],
  
    horror: [
      "Psychological Horror",
      "Gothic Horror",
      "Paranormal Horror",
      "Slasher",
      "Survival Horror",
      "Cosmic Horror",
      "Monster Horror",
      "Haunted House",
      "Splatterpunk",
      "Folk Horror",
      "Thriller Horror",
      "Zombie Apocalypse",
    ],
  
    romance: [
      "Contemporary Romance",
      "Historical Romance",
      "Fantasy Romance",
      "Romantic Comedy",
      "Dark Romance",
      "Slow Burn",
      "Enemies to Lovers",
      "Friends to Lovers",
      "Forbidden Love",
      "LGBTQ+ Romance",
      "Second Chance Romance",
      "Tragic Romance",
    ],
  
    historicalFiction: [
      "War Fiction",
      "Ancient Civilizations",
      "Medieval",
      "Regency / Victorian",
      "Biographical Fiction",
      "Historical Romance",
      "Alternate History",
      "Colonial Era",
      "Renaissance",
      "Industrial Era",
      "Prehistoric Fiction",
      "Western",
    ],
  
    thriller: [
      "Psychological Thriller",
      "Political Thriller",
      "Crime Thriller",
      "Legal Thriller",
      "Techno Thriller",
      "Spy / Espionage",
      "Conspiracy",
      "Medical Thriller",
      "Survival Thriller",
      "Supernatural Thriller",
      "Domestic Thriller",
      "Action Thriller",
    ],
  
    action: [
      "Military Action",
      "Martial Arts",
      "Spy Action",
      "Survival",
      "Revenge",
      "Heist",
      "Heroic Action",
      "Vigilante",
      "Superhero",
      "Post-Apocalyptic Action",
      "Rescue Mission",
      "War Adventure",
    ],
  
    comedy: [
      "Romantic Comedy",
      "Satire",
      "Parody",
      "Dark Comedy",
      "Absurdist",
      "Slapstick",
      "Situational Comedy",
      "Workplace Comedy",
      "Family Comedy",
      "School Comedy",
      "Political Comedy",
      "Fantasy Comedy",
    ],
  
    adventure: [
      "Quest",
      "Journey",
      "Exploration",
      "Expedition",
      "Treasure Hunt",
      "Survival",
      "Lost World",
      "Discovery",
      "Island Adventure",
      "Escape",
      "Sea Voyage",
      "Space Adventure",
    ],
  
    drama: [
      "Family Drama",
      "Romantic Drama",
      "Political Drama",
      "Social Drama",
      "Psychological Drama",
      "Friendship Drama",
      "School Drama",
      "Medical Drama",
      "Legal Drama",
      "Tragedy",
      "Coming-of-Age Drama",
      "Melodrama",
    ],
  
    crime: [
      "Detective",
      "Police Procedural",
      "Mafia / Gangster",
      "Heist",
      "Noir",
      "Courtroom Drama",
      "Vigilante Crime",
      "Political Crime",
      "Organized Crime",
      "Cybercrime",
      "Serial Killer",
      "Kidnapping",
    ],
  
    sliceOfLife: [
      "School Life",
      "Family Life",
      "Friendship",
      "Work Life",
      "Romance",
      "Daily Struggles",
      "City Life",
      "Small Town Life",
      "Growing Up",
      "Cultural Slice",
      "Parenthood",
      "Self-Discovery",
    ],
  
    paranormal: [
      "Ghosts",
      "Vampires",
      "Werewolves",
      "Witches",
      "Reincarnation",
      "Angels and Demons",
      "Psychic Powers",
      "Necromancy",
      "Curses",
      "Exorcism",
      "Reapers",
      "Haunted Objects",
    ],
  
    literary: [
      "Realist Fiction",
      "Experimental",
      "Psychological",
      "Symbolic / Allegorical",
      "Philosophical",
      "Social Commentary",
      "Stream of Consciousness",
      "Metafiction",
      "Minimalist",
      "Modernist",
      "Postmodern",
      "Speculative Literary",
    ],
  };
  
export default genreOptions;  